Create pythonpackage.yml to run a CI build
automata-tech/eva_python_sdk pull request #25
Opened 2019-11-15 18:04 UTC by LouisBrunner

2019-11-20 10:59 UTC, Charlesworth requested changes
Looks great, linting and removal of unused deps, nice. Pipelines work well. Couple of comments, Also, I'll test it on a Robot just to make sure the linting didn't mess anything up

2019-11-20 10:59 UTC, Charlesworth commented on .github/workflows/publish.yml
> +name: Publish on release
Is this not a bit pointless? Can we get rid of this file and add it later if we need it, as it's redundant?

2019-11-20 10:59 UTC, Charlesworth commented on evasdk/__init__.py
> +"""Eva Python SDK
Not sure about copying the README here, DRY and all. perhaps just link to the README or the github web page?

2019-11-21 11:37 UTC, LouisBrunner commented on evasdk/__init__.py
> +"""Eva Python SDK
That's standard Python practice, the same way you add documentation on every class.

2019-11-21 11:38 UTC, LouisBrunner commented on .github/workflows/publish.yml
> +name: Publish on release
We can, but I think we should automate publishing, no need to have it as a manual process when it's automated in 10 lines and anybody with the right permission can trigger it.

2019-11-21 15:56 UTC, Charlesworth commented on .github/workflows/publish.yml
> +name: Publish on release
Totally agree, but this doesn't do that yet and probably could be another PR in itself.

2019-11-22 16:24 UTC, LouisBrunner commented on .github/workflows/publish.yml
> +name: Publish on release
Oh sorry, I forgot I didn't finish to write it

2019-11-22 16:37 UTC, LouisBrunner commented on .github/workflows/publish.yml
> +name: Publish on release
This should now be fixed

2019-11-22 16:44 UTC, LouisBrunner commented on .github/workflows/publish.yml
> +name: Publish on release
This is now gone and will be in another PR

2019-11-25 11:06 UTC, Charlesworth approved these changes

2019-11-25 11:06 UTC, merged