API/SDK integration test setup
automata-tech/eva_python_sdk pull request #52
Opened 2020-05-20 17:00 UTC by Charlesworth

PR goal: Prepare the test/ directory for a full suite of API/SDK integration tests.

- Added test flags, you need to enable tests manually that require a connection to Eva or have a very long run duration. This is now done with the --runslow and --runrobot flags. Leaving these flags out will not run these tests by default
- Added the Eva_data_test.py as a small example of how I want to format the rest of the API/SDK integration level tests.
- Updated the docs with more test run script examples

Follow on PRs will include:
- Fixing the CI pipe so that it runs the test suite
- Adding the rest of the Eva_*_test.py tests for increased API/SDK integration testing coverage

2020-05-21 09:56 UTC, LouisBrunner requested changes
Apart from `pytest` invocation, LGTM

2020-05-21 09:56 UTC, LouisBrunner commented on README.md
> +$ python -m pytest tests/<test-name>_test.py
That doesn't seem right? Also is it worth adding a `[scripts]` in the Pipfile so people can just run `pipenv run test`? https://pipenv-fork.readthedocs.io/en/latest/advanced.html#custom-script-shortcuts

2020-05-22 08:22 UTC, Charlesworth commented on README.md
> +$ python -m pytest tests/<test-name>_test.py
hahaha, good catch, it's a straight copy and paste, should have been `tests/`. I'll change and add the `pipenv run test`

2020-05-27 10:49 UTC, LouisBrunner approved these changes

2020-05-27 10:49 UTC, LouisBrunner commented on tests/conftest.py
> +    if config.getoption("--runslow"):
Might want a function to do this in the future if we get more flags

2020-05-27 10:49 UTC, merged