Eva io get/set tests
automata-tech/eva_python_sdk pull request #55
Opened 2020-05-27 15:47 UTC by Charlesworth

Add SDK tests for Eva object's GPIO get and set methods:
- Added --io_loopback flag for tests that require a head and base io loopback cables
- Added IO tests for getting IO states and and setting digital outputs
- Added loopback tests for digital IO

2020-05-27 15:50 UTC, LouisBrunner requested changes

2020-05-27 15:50 UTC, LouisBrunner commented on tests/conftest.py
> +    if not config.getoption("--io_loopback"):
I think we should start abstracting this, it's the same code with 2-3 differences

2020-05-27 16:17 UTC, Charlesworth commented on tests/conftest.py
> +    if not config.getoption("--io_loopback"):
agree, added a list of tuples to make adding test marks easier, as there are still a few new ones required

2020-05-28 09:21 UTC, LouisBrunner approved these changes

2020-05-28 09:28 UTC, merged