add no auth api call method.  fix api versions bug.
automata-tech/eva_python_sdk pull request #58
Opened 2020-06-25 11:41 UTC by IsaacHook

2020-06-25 13:17 UTC, LouisBrunner requested changes

2020-06-25 13:17 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        r = self.__api_request('GET', 'versions', version=None)
Use your new `api_call_no_auth`? Maybe extend it to other functions which don't use auth?

2020-06-25 13:17 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            headers.update(auth)
That might mess with `auth_create_session`. Also I am not sure we should update arguments given as reference by a user?

2020-06-25 14:20 UTC, IsaacHook commented on evasdk/eva_http_client.py
> +            headers.update(auth)
How would it mess wit `auth_create_session`?   Doesn't it just get a `session_token`?

Wouldn't users always want the correct authentication to be added?  Or are you saying that sometimes users may want to send a request with their own session token not attributed to the instance of EvaHTTPClient?

2020-06-30 13:24 UTC, LouisBrunner approved these changes

2020-06-30 13:24 UTC, merged