added rotation conventions to IK
automata-tech/eva_python_sdk pull request #70
Opened 2020-11-18 20:50 UTC by frusciante8989

This PR deals with the addition of standard rotation methods to the IK. In particular, on top the existing quaternion, teh following have been added:
- rotation matrices
- axis angle
- yaw pitch and roll
If no orientation type is specified, the orientation will default to quaternion, hence maintaining the current behaviour of the method.

2020-11-19 16:13 UTC, LouisBrunner requested changes

2020-11-19 16:13 UTC, LouisBrunner commented on evasdk/Eva.py
> +        self.__http_client = EvaHTTPClient(parsed_host_ip, token, request_timeout=request_timeout,
Why are there extra newlines everywhere?

2020-11-19 16:13 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
`dcm` means nothing to me, would `matrix` makes more sense? We should also document row vs column major

2020-11-19 16:13 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        - 'ypr': yaw, pitch, roll Tait-Bryan angles -> {'yaw': float, 'pitch': float, 'roll': float}
I think `euler` might be better than `ypr` as that seem a bit obscure a name? (even thought Yaw/Pitch/Roll is definitely more explicit)

2020-11-19 16:13 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            result = pyrot.quaternion_from_matrix(pyrot.check_matrix(dcm))
Can you define `result` before the conditions? (as `None` is fine)

2020-11-19 16:13 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            eva_error('calc_inverse_kinematics invalid "{}" orientation_type '.format(orientation_type))
f-literal?

2020-11-19 16:19 UTC, frusciante8989 commented on evasdk/Eva.py
> +        self.__http_client = EvaHTTPClient(parsed_host_ip, token, request_timeout=request_timeout,
They were all longer than 150 characters

2020-11-19 16:19 UTC, frusciante8989 commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
yep, can change that to matrix. 'DCM' is the technical term (direct cosine matrix)

2020-11-19 16:22 UTC, frusciante8989 commented on evasdk/eva_http_client.py
> +        - 'ypr': yaw, pitch, roll Tait-Bryan angles -> {'yaw': float, 'pitch': float, 'roll': float}
Actually, Euler is a bit generic (ypr is a special case of euler angles). We could use `euler_zyx`

2020-11-19 16:24 UTC, frusciante8989 commented on evasdk/eva_http_client.py
> +            eva_error('calc_inverse_kinematics invalid "{}" orientation_type '.format(orientation_type))
Can move to f strings, sure. Since we're here I can also update the other print in this file to f-strings

2020-11-19 18:05 UTC, frusciante8989 commented
@LouisBrunner Modified naming convention as discussed. Added additional check on quaternion norm (needs to be equal to 1): this ensure IK is as accurate as possible. Should be good to go now.

2020-11-19 23:36 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
I think nested arrays are fine, just a question of documenting what the ordering is in your comment

2020-11-19 23:36 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        - 'ypr': yaw, pitch, roll Tait-Bryan angles -> {'yaw': float, 'pitch': float, 'roll': float}
Oh yeah, I wanted to mention that, good point

2020-11-19 23:40 UTC, frusciante8989 commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
Since the columns in the matrix are also the axis of the frame, makes sense to have them in the `col_x`, `col_y`, `col_z` format. I'll probably write a detailed section on the different angular transformation in the docs

2020-11-20 17:39 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
Honestly it doesn't look super straight-forward like this... you would need to write this right?
```python
{
  "col_x": [0, 1, 2],
  "col_y": [3, 4, 5],
  "col_z": [6, 7, 8],
}
```
Which looks a bit odd, versus the more standard:
```python
[
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
]
```
?

2020-11-20 17:41 UTC, frusciante8989 commented on evasdk/eva_http_client.py
> +        - 'dcm': rotation matrix -> {'dcm': 3x3 float array}
So supplying the matrix directly instead of the columns?

2020-11-20 18:26 UTC, LouisBrunner approved these changes

2020-11-20 18:29 UTC, merged