feat: expose globals edit
automata-tech/eva_python_sdk pull request #73
Opened 2021-05-17 15:17 UTC by tallpress

Changes:

- Exposes globals_edit to Eva.
- Fixes failing TestEva_API test by using requests_mock decorator
- Adds note about failing test_get

2021-05-17 15:19 UTC, tallpress commented on README.md
> +- [Eva Python SDK ![PyPI version](https://badge.fury.io/py/evasdk) ![Build status](https://github.com/automata-tech/eva_python_sdk/workflows/Build%20and%20test/badge.svg) [![codecov](https://codecov.
not sure where this came from, feel like this is the new bade or something, can remove if this is an issue

2021-05-17 15:20 UTC, tallpress commented on README.md
> +    - [evasdk.eva_http and evasdk.eva_ws](#evasdkeva_http-and-evasdkeva_ws)
same with this, auto generated

2021-05-17 15:26 UTC, LouisBrunner requested changes

2021-05-17 15:26 UTC, LouisBrunner commented on README.md
> +- [Eva Python SDK ![PyPI version](https://badge.fury.io/py/evasdk) ![Build status](https://github.com/automata-tech/eva_python_sdk/workflows/Build%20and%20test/badge.svg) [![codecov](https://codecov.
It would be good to see where this is coming from, it looks like a copy from the title?

2021-05-17 15:34 UTC, tallpress commented on README.md
> +- [Eva Python SDK ![PyPI version](https://badge.fury.io/py/evasdk) ![Build status](https://github.com/automata-tech/eva_python_sdk/workflows/Build%20and%20test/badge.svg) [![codecov](https://codecov.
yeah, does on autosave, will remove

2021-05-17 15:38 UTC, tallpress commented on README.md
> +    - [evasdk.eva_http and evasdk.eva_ws](#evasdkeva_http-and-evasdkeva_ws)
@LouisBrunner you want me to remove this diff?

2021-05-18 18:03 UTC, LouisBrunner approved these changes

2021-05-25 16:09 UTC, merged