feature: check SDK version upon creating a new auth session
automata-tech/eva_python_sdk pull request #74
Opened 2021-05-19 13:16 UTC by tallpress

https://github.com/automata-tech/eva_python_sdk/issues/45

- Upon creating a new authentication session, the version of the SDK is checked against the version of Eva's software. This is to enforce users to use the correct version of the SDK with their robot.
- I ended up going in with the go-like errors, happy to change these if they aren't particularly pythonic? 
- `__EVA_VERSION_COMPATABILITY` could live in a config file somewhere? Maybe overkill?
- As we can't include this in old versions of the SDK, this will come into play as we release versions.

**IMPORTANT** A bit of maintenance of the version compatibility will be required from developers. Keeping __EVA_VERSION_COMPATABILITY in tact will be very important.

2021-05-19 14:28 UTC, LouisBrunner requested changes

2021-05-19 14:28 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +        return ''
Let's not rely on empty string for no error, return `None`?

2021-05-19 14:28 UTC, LouisBrunner commented on evasdk/version.py
> +__EVA_VERSION_COMPATABILITY = {
What's the point of having old versions?
Also let's imagine we release SDK 4.2.0 with these changes and then Eva 5.0.0 and it's not compatible anymore, this function would still show it as compatible.

2021-05-19 14:28 UTC, LouisBrunner commented on evasdk/version.py
> +    if isinstance(eva, p_version.LegacyVersion):
What is this?

2021-05-19 14:54 UTC, tallpress commented on evasdk/version.py
> +    if isinstance(eva, p_version.LegacyVersion):
I put some info in the docstring, if parse encounters something that isn't semver then it returns a LegacyVersion with the non-semver version in, for example 
```python
 from packaging import version
a = version.parse('3.6.0-dev-tet')
print(a) # <LegacyVersion('3.6.0-dev')>
b = version.parse('3.5.3')
print(b) # <Version('3.5.3')>
```
The idea being we want to be able to use the SDK if we are developing stuff on the robot, and thus our Eva version is something like 3.6.0-dev.
In the case it is something like 3.6.0-dev, we then use regex to get the semver from it, allowing for the compatibility functionality to still work. 
I did think about moving the regex before the parsing, however, I think I prefer it this way around, not really sure why though 😬 , guess it saves on unnecceary regex checking

2021-05-19 14:59 UTC, tallpress commented on evasdk/version.py
> +__EVA_VERSION_COMPATABILITY = {
I guess for consistency if anything... however I am happy to remove all the old versions if you would prefer?

I think in your scenario, we would update this dictionary from
```python 
__EVA_VERSION_COMPATABILITY = {
  '4.2.0': {
    'first': '4.6.0',
    'last': LATEST
}
```
to something like 
```python 
__EVA_VERSION_COMPATABILITY = {
  '4.2.0': {
    'first': '4.6.0',
    'last': '4.6.5' # last supported version that SDK 4.2.0 supports
}
```

2021-05-25 16:24 UTC, LouisBrunner requested changes

2021-05-25 16:24 UTC, LouisBrunner commented on evasdk/version.py
> +    """Takes a version and extracts the semver from it.
`3.1.1-dev-alpha1` is valid semver, if `semver` doesn't handle it use another library (I had to do that in the past)

2021-05-25 16:24 UTC, LouisBrunner commented on evasdk/version.py
> +    if isinstance(eva, p_version.LegacyVersion):
Ok, as I mentioned in another comment, just use a more feature-rich library for semver instead of a non-compliant one.

2021-05-25 16:24 UTC, LouisBrunner commented on evasdk/version.py
> +__EVA_VERSION_COMPATABILITY = {
My point is that no one would benefit from this because by the point you release `4.3.0` and make the above change, you aren't on `4.2.0` anymore so you don't get any use from this.
I am guessing for simplicity, should we just have the "minimum version supported" and that's it?

2021-05-28 10:39 UTC, tallpress commented on evasdk/version.py
> +    """Takes a version and extracts the semver from it.
👍  have gone with semver

2021-06-01 09:58 UTC, LouisBrunner requested changes
Still not convinced about the whole version checking, let's have a meeting about this

2021-06-01 09:58 UTC, LouisBrunner commented on evasdk/version.py
> +def compare_version_compatability(
`compatibility` typo

2021-06-01 09:58 UTC, LouisBrunner commented on evasdk/version.py
> +        return f'unsupported version: SDK version "{sdk_version}" does not exist'
That seems dangerous, if we forget to manually add a new version in the file before pushing, then the package is completely unusable

2021-06-02 08:14 UTC, tallpress commented
> Still not convinced about the whole version checking, let's have a meeting about this

Sure, have put one in the calendar

2021-06-07 11:28 UTC, LouisBrunner requested changes

2021-06-07 11:28 UTC, LouisBrunner commented on README.md
> +| 4.0.0         | 3.1.0 - 5.0.0         |
Just do `+` or `and later` for simplicity?

2021-06-07 11:28 UTC, LouisBrunner commented on evasdk/version.py
> +        return f'unsupported version: exceeded version requirement failure: {compatibility_msg}'
This message is not super clear, moreover I think you can just do a custom message for each

2021-06-07 11:28 UTC, LouisBrunner commented on evasdk/version.py
> +        return f'unsupported version: {e}'
I think for the first few releases, I would prefer if we logged an error and didn't return one, until we are sure our system is working well

2021-06-07 11:28 UTC, LouisBrunner commented on evasdk/version.py
> +_earliest_eva_supported = '3.0.0'
If you create a dataclass, why not store these directly inside?

2021-06-07 11:28 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            eva_error(f'auth_create_session error: using wrong SDK version {err}')
Maybe "incompatible SDK: {err}" might be good enough? The user doesn't know it's know/care it's about auth_create_session and "wrong" sounds a bit strong?

2021-06-07 11:28 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            return f'SDK compatibility error: {err}'
That's a lot of error wrapping, the final one currently look like `auth_create_session error: using wrong SDK version SDK compatibility error: unsupported version: exceeded version requirement failure: SDK version "{sdk_version}" supports Eva versions "{eva_requirements.min}" to "{eva_requirements.max}" exclusive` which is a lot!

2021-06-09 08:00 UTC, tallpress commented on evasdk/version.py
> +        return f'unsupported version: {e}'
will get this to return and then caller can log

2021-06-09 08:18 UTC, tallpress commented on evasdk/eva_http_client.py
> +            return f'SDK compatibility error: {err}'
should now read, `incompatible SDK: Eva is version "{eva_version}". Current SDK version is "{sdk_version}", which supports Eva versions "{eva_requirements.min}" to "{eva_requirements.max}" exclusive`.

2021-06-11 13:54 UTC, LouisBrunner requested changes

2021-06-11 13:54 UTC, LouisBrunner commented on README.md
> +| 3.0.0         | 3.1.0                 |
Same comment as before?

2021-06-11 13:54 UTC, LouisBrunner commented on evasdk/version.py
> +        return str(e)
As in my previous comment, should we block the user in case there is an issue with either version?

2021-06-11 13:54 UTC, LouisBrunner commented on evasdk/version.py
> +    return ''
Return `None`?

2021-06-11 14:04 UTC, tallpress commented on evasdk/version.py
> +        return str(e)
I've moved the logging to the caller, so if there is any version issue, an error is logged, and the requests to the robot continue as per normal

2021-06-11 14:04 UTC, tallpress commented on evasdk/version.py
> +        return str(e)
```python 
def auth_create_session(self):
    self.__logger.debug('Creating session token')

    err = self._check_version_compatibility()
    if err is not None:
        self.__logger.error(f'incompatible SDK: {err}')
```

2021-09-09 13:54 UTC, tallpress commented
replaced by https://github.com/automata-tech/eva_python_sdk/pull/90

2021-09-09 13:54 UTC, closed without merging