feature: adds sphinx documentation and RTD infra
automata-tech/eva_python_sdk pull request #75
Opened 2021-05-20 10:11 UTC by tallpress

Changes
- adds Spinx dep. to create documentation. Installs Sphinx dep to generate module documentation https://www.sphinx-doc.org/en/master/
- adds dep. m2r2 to Sphinx include `README.md` in the docs https://crossnox.github.io/m2r2/
- adds .readthedocs.yaml, which should mean that RTD can read and build our docs with Sphinx.

TODO:
- Add in some documentation to `README.md` about how to update the docs when developing

2021-05-28 12:02 UTC, LouisBrunner requested changes

2021-05-28 12:02 UTC, LouisBrunner commented on .github/workflows/build.yml
> +        uses: EndBug/add-and-commit@v7
I am not convinced by that

2021-05-28 12:02 UTC, LouisBrunner commented on .github/workflows/build.yml
> +        run: pip install Sphinx ; pip install m2r2
Use pipenv?

2021-05-28 12:02 UTC, LouisBrunner commented on README.md
> +sphinx-apidoc -f  -o . ..
Add it to the Makefile?

2021-05-28 12:07 UTC, tallpress commented on .github/workflows/build.yml
> +        uses: EndBug/add-and-commit@v7
how come?

2021-05-28 13:04 UTC, tallpress commented on .github/workflows/build.yml
> +        run: pip install Sphinx ; pip install m2r2
sure, can use the current Pipfile. My only concern is maybe it's a little overkill to create a virtualenv on the unbuntu instance just to install sphinx and m2r2?

2021-09-03 14:48 UTC, tallpress commented
closing in favour of https://github.com/automata-tech/eva_python_sdk/pull/89

2021-09-03 14:48 UTC, closed without merging