Added CD features
automata-tech/eva_python_sdk pull request #83
Opened 2021-07-05 13:09 UTC by Moronibot

Changes:

- Added in the function collision_detection to allow enabling of collision detection including the sensitivity
- Added in the function acknowledge_collision as it is required post-collision
- IDE removed some whitespaces/formatting it wasn't happy with
- Added collision state to the RobotState

2021-07-05 13:58 UTC, LouisBrunner requested changes

2021-07-05 13:58 UTC, LouisBrunner commented on evasdk/Eva.py
> +    def collision_detection(self, on_off, setting):
`set_collision_detection`, `configure_collision_detection` or similar would be better

2021-07-05 13:58 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> -
Minimum amount of changes please

2021-07-05 13:58 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            eva_error('collision_detection error, no such sensitivity ' + setting)
We really shouldn't be using `eva_error` here but I guess that's what we have done so far... Maybe start switching to `raise ValueError`?

2021-07-05 13:58 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            eva_error('collision_detection error, must be True/False')
Same here

2021-07-05 13:58 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +    def acknowledge_collision(self):
Due to being a `controls/` endpoint, I think it should at least work like the `control_*` functions with the `wait_for_ready` et al
Maybe even being called with the `control_` prefix

2021-07-05 14:16 UTC, tafautomata commented on evasdk/Eva.py
> +    def collision_detection(self, on_off, setting):
`enabled` might be more descriptive than `on_off` as func. parameter name, and maybe `sensitivity` for `setting`

2021-07-05 15:20 UTC, LouisBrunner requested changes

2021-07-05 15:20 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            raise ValueError('control_collision_detection error')
Sorry, misunderstanding: request related exceptions should stay `eva_error`, arguments errors should be `ValueError`, so `r.status_code` in both functions should stay `eva_error`

2021-07-05 15:20 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +            time.sleep(0.1)
Add the same comment?

2021-07-06 11:56 UTC, walker-j approved these changes, later dismissed
Tested against 4.9.0, lgtm

2021-07-06 11:56 UTC, walker-j commented on evasdk/eva_http_client.py
> +        if r.status_code != 200:
```suggestion
        if r.status_code != 204:
```

2021-07-07 22:38 UTC, walker-j commented
Closing this PR as these changed were included in PR #84

2021-07-07 22:38 UTC, closed without merging