Feature/docstrings
automata-tech/eva_python_sdk pull request #88
Opened 2021-09-01 11:45 UTC by Moronibot

Added docstrings to all valid functions within Eva.py

Fixes #77

2021-09-01 14:54 UTC, LouisBrunner requested changes, later dismissed
Really nice initiative, lots of good stuff in there, especially the examples, however a lot of the description aren't really readable English and use confusing language (e.g. every single `control_` endpoint use a different phrasing even though they all do nearly the same thing)

I commented on most of the issues but this need a few iterations of polishing the descriptions

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +    def control_resume(self, wait_for_running=True):
Mmmmh it is a breaking change though...

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            headers: set automatically within EvaHTTPClient
I think this should `extra headers you want to add` or similar

Might be good to mark `optional` arguments as such

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            version: API server version
Probably should specify you should never touch this

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            dict: containing results of API call
Result is a `requests.Response` object https://docs.python-requests.org/en/latest/api/#requests.Response

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            EvaError: If status code on API request is not 200
Fairly sure this only throws `EvaAutoRenewError` if it fails to automatically login or `requests`'s own exceptions in case of http failures

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Makes a direct API call to EVA to endpoints that do not require authentication
Same issues as above

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Gets the version of the API server and the Choreograph version installed on the robot.
Maybe `API versions supported by the server` might be more accurate/understandable?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            EvaError: If status code on API request is not 204
I think you don't need to specify the status code, just `if it isn't successful` should be enough and less brittle

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            Should not need to be called as it is handled
+ internally?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            list: 6 position list containing joint angles in RADIANS
`list of 6 joint angles in radians`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            pin_type: input or output ping type
`ping`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            string: pin status
Actually a boolean or float based on the `pin_type`

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            EvaError: gpio_get error, no such pin
`if the pin doesn't exist`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            EvaError: gpio_get error, pin_type must be "input" or "output"
`or if the pin_type is invalid`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            dict: JSON dictionary of the HTTP request
Just a dict of the data, no need to specify JSON or HTTP

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            keys: key name of the value to change
List of keys of values to change...

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            values: value to change global to
...and their associated new value

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Retrieves the toolpath specified in JSON format
`specified toolpath`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            dict: JSON formatted dictionary containing all toolpath data
No JSON

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Saves a toolpath file to the robot
-`file`

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            toolpath: JSON dict formatted toolpath
not JSON

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Saves a toolpath file to the robot
`Create a new toolpath or update an existing one (if the name is already used)`

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            toolpathId: toolpath ID number on the toolpaths_list() if successful
`toolpath ID for the newly created or updated toolpath`

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            toolpathId: id integer of the toolpath called upon
`of the toolpath to use`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            This does not save the toolpath to the toolpaths_list
`to the robot`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            toolpathRepr: JSON formatted dictionary containing all toolpath data
Not JSON

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Sets the toolpath passed to it as the active toolpath
Sets the robot's active toolpath, which can be run, homed, etc

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            dict: JSON formatted dictionary containing all toolpath data
Returns nothing

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            This is used within EvaWithLocker and does not need to be called separately
`unless you don't use with eva.lock():`?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            This is used within EvaWithLocker and does not need to be called separately
Same

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            None, once robot has reached specified state
I don't think you need to repeat it

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            loop: integer, number of loops to run toolpath for
`0` means loop forever

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Sends robot to home/start position of the active toolpath
Worth adding a note on all motion endpoints that `teach` mode requires the lock

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Changes the state of the output pin
Note: requires the lock?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +        """Applies choreograph update to robot.
Note: requires the lock?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            time_sec: time in seconds of duration to travel to joint angles specified
`max_speed` and `time_sec` are mutually-exclusive

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            EvaError: If status code on API request is not 200
In a lot of this case, telling that it will fail if it's not 200 is not super useful, adding stuff like `if the robot is not in running mode` instead of putting as a note is much better

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            fk_type: 'position', 'orientation', 'both' are available FK types
Description of what they mean?

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            dict: containing 'result', 'success', and 'orientation'
Depends on fk_type

2021-09-01 14:54 UTC, LouisBrunner commented on evasdk/Eva.py
> +            guess: a list of joing angles in RADIANS near the area of operation, does not need to be precise
arguable

2021-09-01 23:28 UTC, LouisBrunner commented on evasdk/eva_http_client.py
> +    def control_resume(self, wait_for_running=True):
That's my plan

2021-09-09 14:57 UTC, tallpress commented on evasdk/Eva.py
> +        """Returns a property from the data_snapshot dict.
big nitpick: some of the descriptions end in full stops (like the one above), others don't. Either is good, I think my preference would be end with a full stop.

2021-09-14 15:03 UTC, tallpress approved these changes
:shipit: very nice

2021-09-14 15:14 UTC, merged