feat: documentation genereated on orphan branch
automata-tech/eva_python_sdk pull request #89
Opened 2021-09-03 14:48 UTC by tallpress

dupe of https://github.com/automata-tech/eva_python_sdk/pull/75, however not a folk

This is how the docs will appear https://eva-python-sdk-testing.readthedocs.io/en/feature-documentation/evasdk.html url will change
Changes

adds Spinx dep. to create documentation. Installs Sphinx dep to generate module documentation https://www.sphinx-doc.org/en/master/
adds dep. m2r2 to Sphinx include README.md in the docs https://crossnox.github.io/m2r2/
adds .readthedocs.yaml, which should mean that RTD can read and build our docs with Sphinx.
removes badges from README.md heading as it was messing with the table of contents
adds RTD automation step that will automatically build semver tagged versions of the SDK's documentation

2021-09-06 12:55 UTC, LouisBrunner requested changes

2021-09-06 12:55 UTC, LouisBrunner commented on .github/workflows/docs.yml
> +        run: pip install Sphinx ; pip install m2r2
`pip install Sphinx m2r2`?

2021-09-06 12:55 UTC, LouisBrunner commented on .github/workflows/docs.yml
> +        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
Is that the recommended way? I thought it was `echo :set-output:` or something

2021-09-06 12:55 UTC, LouisBrunner commented on .github/workflows/docs.yml
> +          make api_docs
`make -C docs api_docs`

2021-09-06 12:55 UTC, LouisBrunner commented on docs/evasdk.rst
> +evasdk package
Do we need to include those or are they auto-generated? Do we keep them so we can edit them and add more docs? Is that something we can do with docstring on the package itself?

2021-09-06 12:55 UTC, LouisBrunner commented
What about development version of the docs? Does that come in a latter PR?

2021-09-06 13:42 UTC, tallpress commented on docs/evasdk.rst
> +evasdk package
this is generated, most are generated, this is what sphinx uses to generate the docs off of the docstrings and set up the display of the documentation. However, there are a few custom ones, such as `example.rst` `index.rst` and `readme.rst`

2021-09-06 13:43 UTC, tallpress commented on .github/workflows/docs.yml
> +        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
tbh this was the way i could find that worked - quite a few places had something like the above

2021-09-06 13:49 UTC, tallpress commented
> What about development version of the docs? Does that come in a latter PR?

good point, I can add in another PR, or add in this PR, up to you. It would be a matter of also running this workflow (or similar one with hardcoded `docs/development`) to also run when merging into development.

2021-09-06 16:09 UTC, LouisBrunner requested changes

2021-09-06 16:09 UTC, LouisBrunner commented on .github/workflows/docs.yml
> +        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
I would prefer using the documented way if possible: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
Also, you don't need to do ```
`echo $()`
```, it's the same as doing `$(git)` (or
```
`git`
```
)

2021-09-06 16:09 UTC, LouisBrunner commented on docs/evasdk.rst
> +evasdk package
My point is: can we avoid these custom ones through docstrings? Can we remove any autogenerated one?

2021-09-06 16:27 UTC, tallpress commented on docs/evasdk.rst
> +evasdk package
we need the `index.rst` and `modules.rst`. I think it's useful for the docs to include the readme, hence the `readme.rst`, and also nice to show the examples, hence `examples.rst`. However happy to remove all that if you don't want it. Regarding the generated files, we can remove `evasdk.rst` and `setup.rst` if you like, i guess they aren't necessarily required anymore now that we are building the docs on an orphan branch.

2021-09-06 16:34 UTC, tallpress commented on .github/workflows/docs.yml
> +        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
would you rather use set-output or env vars https://docs.github.com/en/actions/reference/environment-variables. I might be wrong but set-output looks like it might be for inter action comms
```
output values used by other actions
```

2021-09-07 13:21 UTC, LouisBrunner commented on .github/workflows/docs.yml
> +        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
Well you are defining an action which has an output, so that's literally what it's for
The only thing that link shows is how to create constant env vars at the beginning of your workflow?

2021-09-07 13:24 UTC, LouisBrunner commented on .readthedocs.yaml
> +   - requirements: docs/requirements.txt
Why do we need extra packages?

2021-09-07 13:26 UTC, LouisBrunner commented on docs/evasdk.rst
> +evasdk package
`readme.rst` I can understand, `examples.rst` I don't love but it's alright, why do the others do?

2021-09-07 14:54 UTC, tallpress commented on docs/evasdk.rst
> +evasdk package
index.rst is the glue. modules.rst means we display the module documentation, it effectively tells the Sphinx autodoc tool "hey look, use the to generate docs off of these modules"

2021-09-08 07:40 UTC, tallpress commented on .readthedocs.yaml
> +   - requirements: docs/requirements.txt
it's so RTD can build the documentation. I think it must parse the files, as without giving the requirements listed it freaks.

2021-09-09 13:33 UTC, LouisBrunner approved these changes

2021-09-09 13:33 UTC, merged